### ISSUE TITLE
gh-pageの設定

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#1]
docsフォルダの中身が，
https://paperanno.github.io/paperanno/
に表示されるようになっていますので，ここにデモを移動する．

**Comment by yoheiMune** [comment]
お世話になっております。

こちらの件を対応しました。
paperannoレポジトリで別ブランチを作りそちらにコミットしたのちに、プルリクを作成しました。
こちらは僕の方でマージしてしまってもよろしいでしょうか？
https://github.com/paperai/paperanno/pull/1

どうぞよろしくお願いします。

**Comment by hshindo** [comment]
はい，マージしてください．

**Comment by yoheiMune** [comment]
了解いたしました！

**Comment by yoheiMune** [comment]
マージして、下記ページが表示されることを確認しました。
https://paperai.github.io/paperanno

すみません、上記をアップして気づいたのですが、初めての表示の場合にユーザーがロードしたファイルがないためpdf.jsでのコンテンツなしの表示となっていました。こちらは表示対象ファイルがない場合にはロードをするように促すように修正します（もしくは何か初期表示で表示すべきサンプルなどありますでしょうか？）。

よろしくお願いします。

**Comment by hshindo** [comment]
では，docsの中に以下のpdfを置いていただき，サンプルにしていただけないでしょうか？
http://www.aclweb.org/anthology/P12-1046

**Comment by yoheiMune** [comment]
お世話になっております。
上記のpdfが初期表示となるように修正しました。
お手隙の際にご確認お願いします。
よろしくお願いします。

**Comment by hshindo** [comment]
OKです．有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
