### ISSUE TITLE
linkの追加

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#10]
アノテーションの種類として，向きが無い矢印（リンクと呼ぶ）を追加したいと思います．実装は，arrowと同じものを使ってください．
複数の要素をグループ化するときに使います．

index.htmlだけ書き換えました．
https://github.com/paperai/paperanno/pull/7

annoファイルは，
```
"rel-1": [
  1,
  "link",
  "span-1",
  "span-3",
  "rel-1"
]
```
のような感じで良いと思います．

**Comment by yoheiMune** [comment]
こちら了解致しました！

**Comment by yoheiMune** [comment]
お疲れ様です。
こちらの件について作成されています以下のプルリクについて、masterブランチかpdfanno-2ブランチに取り込みをさせていただきたいのですが、問題ありませんでしょうか？
https://github.com/paperai/paperanno/pull/7

どうぞよろしくお願いします。

**Comment by hshindo** [comment]
はい，自由にmergeしていただいて構いません．

**Comment by yoheiMune** [comment]
ありがとうございます。

**Comment by hshindo** [comment]
確認致しました．問題なさそうです．
有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
