### ISSUE TITLE
ファイル選択ＵＩの改善

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#11]
index.htmlを改善したいと思います．
特に，paper, primary annotation, secondary annotationのファイルを選択する部分です．

変更点：
1.  paper (.pdf) のファイル参照ボタンを削除．代わりに，ユーザーはviewer領域にpdfファイルをＤ＆Ｄしてファイルを読み込むようにする．
2.  primary annotation (.anno), secondary annotation (.anno)の部分を，以下のように変更．

![1](https://cloud.githubusercontent.com/assets/6833527/21250541/624c0f76-c389-11e6-9fa8-e025f42f581d.png)

3. LOADボタンは不要であれば削除

2に関して：
ラジオボタンは，アノテーションをprimary（編集可能）にするかどうかを表す．
カラーピッカーは，ユーザーが表示色を選べる．

カラーピッカーは，以下のものが簡単そうです．
* https://github.com/bgrins/spectrum

READMEにある，CDNによる導入を使いたいと思います．
カラーピッカーの種類は，ドキュメントページの[Hide After Palette Select](http://bgrins.github.io/spectrum/#options-hideAfterPaletteSelect)にしたいと思います．

技術的に困難・煩雑になる，等の問題があれば教えてください．

**Comment by hshindo** [comment]
#12
と関連していると思いますので，そちらも合わせてお願いします．（#12 にもpriorityタグをつけます）

**Comment by yoheiMune** [comment]
お疲れ様です。
遅くなり申し訳ありません、こちらの機能を実装しました。お手隙の際にご確認をお願いいたします。
https://paperai.github.io/paperanno/

また、 #12 #15 も一緒に対応いたしました。
合わせてご確認いただけたら幸いです。

どうぞ宜しくお願いします。

**Comment by hshindo** [comment]
デモ画面の矢印アノテーションが表示されないようですが，そちらの環境では表示されているでしょうか？

**Comment by hshindo** [comment]
カラーパレットは，黒と白は使わないので削除してください．

**Comment by hshindo** [comment]
【修正２】現在のデモでは，一度annoファイルを指定してviewerに表示させてしまうと，それを非表示にすることができないので，ラジオボタンとカラーパレットの間にチェックボックスを設けて，annoファイルの表示・非表示を切り替えられるように変更していただけないでしょうか？
４か所のチェックボックスは，デフォルトではすべてチェックが入っているようにしてください．この場合，ユーザーが参照ボタンを押してannoファイルを指定すれば，自動的にviewerに表示されるという意味になります．チェックを外せば，viewerでは非表示になります．

**Comment by yoheiMune** [comment]
カラーパレット、チェックボックス、それぞれ了解しました。

**Comment by yoheiMune** [comment]
お疲れ様です。
下記3点の対応を行いました。お手隙の際にご確認お願いできますでしょうか？
https://paperai.github.io/paperanno/

* arrowが表示されない不備の修正
* カラーパレットから黒と白を除外
* 表示/非表示のチェックボックスを追加

どうぞ宜しくお願いします。

**Comment by hshindo** [comment]
これで問題なさそうです．
有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。
