### ISSUE TITLE
警告メッセージの出力

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#12]
警告メッセージを出力して，Yesをユーザーが選択した場合に，実際の動作を行う．
ひとまず，思いつくケースは，

* ユーザーが指定した新たなpdfファイルをロードするとき：
  * alert message: "Are you sure to load a new pdf file? Please save your current annotations."
  * button: Yes or No
* DELボタンを押してアノテーションをクリアするとき：
  * alert message: "Are you sure to clear the current annotations?"
  * button: Yes or No

です．
他にも警告メッセージを出したほうが良いケースがあれば教えてください．

実装は，javascript標準のalertメッセージで良いと思います．

**Comment by hshindo** [comment]
alertメッセージですが，
例えば，githubのREADME.mdをブラウザ上で編集している途中で，別の画面へ遷移しようとすると，以下のようなメッセージが出ます．（これはfirefoxの例です）
これはgithub固有のものではなく，ブラウザまたはHTMLなどの標準的な機能のようです．
これと同じものにしていただけないでしょうか？

<img width="1243" alt="default" src="https://cloud.githubusercontent.com/assets/6833527/21472475/b3c02d18-cb1f-11e6-9995-c6cae3429f9a.png">

**Comment by hshindo** [comment]
すみません，もしかしたら通常のjavascript alertでも良いかもしれないので，少々考えさせてください．

**Comment by yoheiMune** [comment]
了解しました！

**Comment by hshindo** [comment]
もう一つ，追加です．

* ユーザーが選択したannoファイルのフォーマットが有効でない場合：
  * message: ***.anno is invalid. （注：***には実際のファイル名が入ります）
  * button: "ok"

**Comment by yoheiMune** [comment]
了解致しました！

**Comment by hshindo** [comment]
ひとまず，javascriptのalertでも良いと思いますので，そのようにお願いします．
私はよく知らないのですが，他にHTML5などで使われる標準的なalertメッセージがあるならば，そちらを使ってください．

**Comment by yoheiMune** [comment]
了解いたしました。上のページから離れる際の確認ダイアログですが、ブラウザ標準の機能で、以下のように使うことができます。
https://developer.mozilla.org/ja/docs/Web/API/WindowEventHandlers/onbeforeunload

常に出るというわけではなくて編集中であれば出るようなものですが、paperannoであればアノテーションを追加/編集して保存していない状態の場合に、ページを離れようとしたら出すという実装がいいかと思います。

よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．ではそのようにお願いします．

**Comment by yoheiMune** [comment]
了解いたしました、実装します。

**Comment by hshindo** [comment]
参照ボタンを押してannoファイルを指定するときは，特にalertメッセージは不要です．
現在は，以下のメッセージが出力されています．
alert message: "Are you sure to load a new pdf file? Please save your current annotations."

これは，pdfを新しくするときなので，pdfをD&Dしたときに出してください．

それから，DELボタンを押してアノテーションをクリアするとき： 
alert message: "Are you sure to clear the current annotations?"
と出力されますが，alert messageの部分は不要ですので，単にAre you sure to clear the current annotations?だけ出力してください．

**Comment by yoheiMune** [comment]
お疲れ様です、こちらのメッセージ不備があり申し訳ありません。
2件とも修正いたしましたので、お手隙の際にご確認をお願いできればと思います。
https://paperai.github.io/paperanno/

宜しくお願いします。

**Comment by hshindo** [comment]
これで問題なさそうです．
有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
