### ISSUE TITLE
fa fa-fontの削除

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#14]
rect, span, arrowのそれぞれにテキストラベルを付与できるようになるので，
従来からあるテキスト機能（デモページのfa fa-fontボタンに相当）は削除したいと思います．

TODO:
* fa fa-fontボタンの削除
* 上記に関連するプログラムコードを削除（リファクタリング）

**Comment by yoheiMune** [comment]
了解致しました。

**Comment by hshindo** [comment]
こちらですが，時間がかからないように思いますので，最優先で行っていただけないでしょうか？
よろしくお願いします．

**Comment by yoheiMune** [comment]
了解です！

**Comment by yoheiMune** [comment]
お疲れ様です。
テキストアノテーションの削除対応を行いました。
https://paperai.github.io/paperanno/

お手隙の際にご確認頂けますと幸いです。
宜しくお願いします。

**Comment by hshindo** [comment]
問題ありません．
有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。

**Comment by hshindo** [comment]
indexブランチが消えているようですが，私が作成して作業しているもののような気がしますので，復活させます．

**Comment by yoheiMune** [comment]
申し訳ありません、宜しくお願いします。
