### ISSUE TITLE
初期ロード時にPDF, アノテーションを読み込まない

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#15]
デモページにアクセスをすると，ユーザーが以前に作業を行ったPDFとアノテーションが最初に読み込まれるようになっていると思います．

このように過去の履歴を記憶しておく必要はない（むしろ，paperannoの仕様が変わったときに弊害がある）ので，この機能を削除しても良いのではないかと思っていますが，現在の実装はどのようになっているのでしょうか？

最初のPDF読み込みと，annoファイルの読み込みは，pdf.jsなどが勝手に行っているのか，それともpaperanno側で行っているのでしょうか？

**Comment by yoheiMune** [comment]
こちらの内容了解致しました。

アノテーションのレンダリング：paperanno側で実施
PDFのレンダリング：pdfjs側で実施

という状況ですが、PDF読み込み対象は指定できますので、このIssueも対応可能と思われます。
よろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．

では，PDFに関しては今と同じままで良いです．（pdf.jsが前回と同じPDFを自動的にロード）
アノテーションは，毎回ユーザーが指定するようにしたいと思いますので，自動でロードする必要はありません．
よろしくお願いします．

**Comment by yoheiMune** [comment]
仕様了解致しました。
