### ISSUE TITLE
ページをまたぐArrowやハイライト

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#3]
https://github.com/pdfanno/pdfanno/issues/11

**Comment by yoheiMune** [comment]
お疲れ様です。
こちら実装を行いました。問題ないかご確認お願いできますでしょうか？
https://paperai.github.io/paperanno/

 * arrowやrectやtextはページを跨いで描画することができるようになりました。
 * ハイライトはブラウザの選択領域の仕様上、ページ間を跨いではできないもの(pdf)が多いようです。
 * アノテーションの基準点を変更しましたので、既存のアノテーションはずれてしまいます。

どうぞよろしくお願いします。

**Comment by hshindo** [comment]
ハイライトを行って，そのあとにpdfの拡大，縮小をするとハイライト領域がずれてしまうようです．

**Comment by yoheiMune** [comment]
すみません、失礼いたしました。
確認して対応します。

**Comment by hshindo** [comment]
rectは，むしろページをまたぐことができないようになっているほうが良いのですが，対応可能でしょうか？
.annoデータが複雑になってしまうことを避けるという意味もあります．

**Comment by yoheiMune** [comment]
rectがページをはみ出さない対応については、実装を追加して対応可能です。

そしてすみません、1点共有が漏れていました。
今回のページをまたぐ対応により、アノテーションのレンダリング方法を変更しています。
具体的には、

◆ 以前
PDFの1ページ毎にレンダリング領域（SVG要素）があり、それに対してレンダリング。そのためページをまたぐような実装が難しかった。

◆ 現在
PDF全体で1つのレンダリング領域（SVG要素）とし、ページという概念を排除。そのためページをまたぐようなアノテーションも描画可能になった。
（こちらはhtmlannoと同様の実装です）

上記の変更のため、.annoファイルについてもページをまたぐRectについても複雑にはなりません。
```
{
	"version": "0.0.1",
	"P12-1046.pdf": {
		"rect-1": [
			1,
			186.086500655308,
			745.9501965923985,
			175.65923984272607,
			117.10615989515072
		]
	}
}
```

こちら、rectがページをはみ出さない制御を追加実装はいかがいたしましょうか？

**Comment by hshindo** [comment]
この場合，座標はページ単位ではなく，pdf全体での座標ということになるのでしょうか？

**Comment by hshindo** [comment]
annoファイルの情報は，ページ単位の座標が書いてあるほうが良いです．

**Comment by yoheiMune** [comment]
はい、おっしゃる通りPDF全体の座標で出力しています。
こちら修正します！

**Comment by hshindo** [comment]
pdf全体の座標と，ページごとの座標は簡単に相互変換可能なのでしょうか？
paperannoでアノテーションを行ったあと，例えばpdfboxのようなソフトウェアを用いて，.annoとpdfファイルから，ハイライトされているテキスト情報などを抽出する予定なので，pdfの解析ソフトと互換性があるほうが好ましいいです．どちらの座標系が標準なのかあまり確信はないのですが，おそらくページごとのほうが標準的なのかという気がしています．

**Comment by hshindo** [comment]
結局，spanがページをまたがないのであれば，arrowのみがページをまたぐことができれば良いということになります．
arrowの情報は，spanやrectとは異なり，座標と関係ない情報ですので，座標系は以前のままで良いのではないかと思いますが，いかがでしょうか？

**Comment by yoheiMune** [comment]
はい、全体座標とページ毎の座標は変換できると思います。
座標系について合わせたいという背景ありがとうございます。理解しました。
全体とページ毎で座標系は相互変換可能なので、以前のように出力するようにします(将来、全体座標でとあればその際にご指示下さい)。
よろしくお願いします。

**Comment by hshindo** [comment]
はい、ではそのようにお願いします。
.annoファイルはページごとの座標系であっても、内部実装上はpdf全体の座標系で処理を行っている（そうしなければページをまたぐ描画ができない）、という理解で正しいでしょうか？

**Comment by yoheiMune** [comment]
はい、内部実装ではページをまたぐ描画のために、pdf全体の座標系を利用したいと思います。
Rectについてもページをまたがない制御を追加するということでよろしいでしょうか？

また、.annoファイルについて、全体座標とページ毎の座標変換のために、以下のようなpdfのメタ情報を追加させて頂いてもよろしいでしょうか？
```js
{
	"P12-1046.pdf": {
		"meta": {
			"w" : 640,     // 追加1：pdfのページ横幅
			"h" : 980,      // 追加1：pdfのページ縦幅
		},
		"span-1": [
			[
				1,
				103.39155944169492,
				317.63684445768774,
				86.92662839468956,
				10.212157330154948
			],
			"spanのテキスト"
		],
/*以下省略*/
```

**Comment by hshindo** [comment]
わかりました。
メタ情報に関しては問題ありません。
Rectはページをまたぐ機能は不要です。

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
それでは上記の内容にて実装させていただきます。
宜しくお願いします。

**Comment by hshindo** [comment]
参考までに，metaが必要なのはなぜでしょうか？

**Comment by yoheiMune** [comment]
お疲れ様です。
.annoファイルにて、座標をページ毎の座標にする件を対応しました。
https://paperai.github.io/paperanno/

下記2件は対応中です。
* ページリサイズ時の表示不備修正
* rectがページをはみ出さない対応

どうぞよろしくお願いします。

**Comment by yoheiMune** [comment]
お疲れ様です。
遅くなり申し訳ございません、上記の2件を対応いたしました。
https://paperai.github.io/paperanno/

お手隙の際にご確認頂けますと幸いです。
どうぞよろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．
.annoデータのダウンロードボタンが効かないのですが，ご確認いただけないでしょうか．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
申し訳ありません、meta情報を追加したことによりデータの保持構造を変更したため、エラーとなっていると思われます。お手数ですがブラウザコンソールで `localStorage.clear()`を実行頂いて、再度ご確認をお願いできますでしょうか？共有が漏れており申し訳ありません。

> 参考までに，metaが必要なのはなぜでしょうか？

回答が遅れてしまい申し訳ありません。こちらですが、PDFごとにサイズが異なる可能性があるためです。ページ全体座標とページ毎の座標間を変換する際に、PDF1ページの高さ/横幅が欲しいところです。.annoファイルは複数のpdfに対するアノテーション情報を持ち、インポート・エクセスポートする際に現在表示しているPDF以外の座標変換も行う必要があるため、PDF毎にmeta情報を持ちたいと考えています。

よろしくお願いします。

**Comment by hshindo** [comment]
「インポート・エクスポートする際に現在表示しているPDF以外の座標変換も行う必要がある」
のはなぜでしょうか？

**Comment by yoheiMune** [comment]
あっそうですね！現在はエクスポート/インポートする際に全てのPDFに関する座標の変換を行なっているため必要ですが、ユーザーがアノテーションの追加/編集をした際に、（表示用の座標に加えて）.annoファイル用の座標も計算しておけば大丈夫ですそうです。そうすればmeta情報はなくてもできそうです。
ありがとうございます。修正してみます。

**Comment by hshindo** [comment]
はい，ではmetaは削除でお願いします．
今までのフォーマットは読み込めないようになっても問題ありません．

**Comment by yoheiMune** [comment]
ご指摘ありがとうございます。修正します。

**Comment by yoheiMune** [comment]
お疲れ様です。上記の修正を行いました。metaデータを削除したため、再度 `localStorage.clear()`を実行頂いたのちにご確認をお願いできますでしょうか？
https://paperai.github.io/paperanno/

基本的にはページ毎の座標を持つようにし、画面にレンダリングするときのみ画面全体の座標系に変換するように修正いたしました。

度重なる確認依頼となり恐縮ですが、どうぞよろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．これで問題ないと思います．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。
