### ISSUE TITLE
テキストボックスのオートコンプリート

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#4]
https://github.com/pdfanno/pdfanno/issues/12

**Comment by hshindo** [comment]
参考までに，Githubのトップページにある左上の検索ボックスは，履歴をdeleteで削除できます．
https://github.com/

**Comment by yoheiMune** [comment]
ありがとうございます。
当方で持ってますMacで確認したところあいにく削除できなかったのですが、以下の検索ボックスの認識であっていますでしょうか？
<img width="1066" alt="2016-12-23 23 28 31" src="https://cloud.githubusercontent.com/assets/1447152/21456147/318df116-c969-11e6-8b0b-ee64c0ba0436.png">

**Comment by hshindo** [comment]
一番左上の，猫のアイコンのすぐ右です．
windows, firefoxでは削除可能です．

**Comment by yoheiMune** [comment]
お忙しいところご確認ありがとうございます。
Windows, Firefox環境で確認してみます。よろしくお願いします。

**Comment by hshindo** [comment]
私の環境ではこんな感じです．

<img width="673" alt="default" src="https://cloud.githubusercontent.com/assets/6833527/21464743/c29c9160-c9ca-11e6-885a-f44c4276cc85.png">

**Comment by yoheiMune** [comment]
お疲れ様です。当方の調査不足で申し訳ありません。調べましたところ入力履歴の削除は、以下のFirefoxの機能のようです。
https://support.mozilla.org/ja/kb/control-firefox-automatically-fills-in-forms

こちらで確認したところ上記記事に記載されている通り「Shift + Delete」で1件ずつ削除できることを確認できました（Github.comのページにて）。ただ、「Deleteのみ」ですと入力補完が非表示になるだけで削除することはできませんでした。

Github.comの左上検索入力欄についてコードベースで見てみましたが、何か特別な実装があるわけではないようで、Firefoxの機能で履歴が1件ずつ削除できるようです。

大変申し訳ありませんが、まだWindows機が入手できていないため、別のpriorityタグが付いたIssueから対応させてください（Windowsサーバーへリモートデスクトップで接続して確認しても再現できませんでした）。今週には確保できると思います。

どうぞよろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．
私の環境（windows10）では，firefoxだとdelete，chromeだとshift+deleteで履歴を削除できましたので，windowsに関してはこれでOKです．

macでも同様にブラウザの標準機能で履歴を削除できるのであれば，特に何か実装する必要はなさそうですので，firefox, chromeについてご確認いただけないでしょうか．

**Comment by hshindo** [comment]
訂正です．
windows10の場合，
* Githubの検索ボックス：
  * Firefox: deleteで履歴削除可能
  * chrome: shift+deleteで削除可能
* paperannoのdemo
  * Firefox: shift+deleteで削除可能
  * chrome: delete, shift+deleteでは削除できない．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
Chromeでも以下の通り入力履歴を削除できるようです（こちらも調査不足で申し訳ありません）。
https://support.google.com/chrome/answer/142893?co=GENIE.Platform%3DDesktop&hl=ja

当方のMacでも以下の通り削除できました（Github.comにて）。
Firefox：Shift + Delete
Chrome：Shift + Fn + Delete

こちらの入力履歴ですが追加されるタイミングは、formをsubmitしたタイミングのようです。Github.comと同じような挙動になるように修正します。

よろしくお願いします。

**Comment by yoheiMune** [comment]
お疲れ様です。ブラウザ標準のオートコンプリート機能が使えるように実装を修正しました。
https://paperai.github.io/paperanno/

お手隙の際にご確認お願いできたらと思います。
よろしくお願いします。

**Comment by hshindo** [comment]
確認致しました．これでOKです．

上記の問題とは別ですが，デモページでハイライトのアノテーションを行ったり，スパンラベルにテキストを入力すると，PDFの画面が左右にずれるのですが，何が原因でしょうか？
今回のcommitから，この現象が起こっているようです．

**Comment by yoheiMune** [comment]
すみません、確認します。

**Comment by yoheiMune** [comment]
お疲れ様です。spanラベル時などに画面が左右にずれる問題を修正しました。
https://paperai.github.io/paperanno/

お手隙の際にご確認をお願いできたら幸いです。
よろしくお願いします。

**Comment by hshindo** [comment]
確認致しました．これで問題ありません．
有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございました。
