### ISSUE TITLE
複数のアノテーションファイルを同時に描画

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#6]
https://github.com/pdfanno/pdfanno/issues/17

**Comment by hshindo** [comment]
こちらの機能を早めに実装できたらと思っていますが，時間がかかりそうでしょうか？

**Comment by yoheiMune** [comment]
昨日時点で半分開発したので、明日にはご確認頂けると思います。お待たせしてすみません、よろしくお願いします。

**Comment by yoheiMune** [comment]
お世話になっております。
お待たせして申し訳ありません。Secondary Annotationsを表示できるように実装しました。認識があっているかご確認お願いします。
https://paperai.github.io/paperanno/

挙動は以下の内容で実装しています。
* 「Secondary annotations」で選択後(複数可)、Loadボタンを押すと読み込む.
* 閲覧モードではマウスオーバー挙動で強調表示（Primary Annotationと同じ）
* 閲覧モードでの編集/移動/削除はできない
* arrow編集時には○印を非表示（起点/終点にできない）
* 色は3色用意（green, blue, purple)で、annoファイルごとに色を分けた


以下挙動についてご希望などありましたらご指示いただけると幸いです。
* Secondary Annotationsを削除するにはどうするか（現在はブラウザのコンソールからlocalStorage.clear()）で削除
* 色のバリエーションは最大何個良いすべきか
* arrowやtextなど何らか編集時は非表示にした方が都合が良いか
* その他

挙動やUI面で細かい点でも是非ご指摘をお願いします。
どうぞよろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．確認しました．これでOKです．

色は，最終的にはユーザーが選べるようにしようと思いますが，ひとまず上記の３色の設定で良いです．
私がindex.htmlを更新して，ユーザーが色を選択できるUI部を追加しますので，そのときに動作部分の設定を行っていただきたいと思います．

挙動ですが，
secondary annotationを削除する，というのは，どういう意味でしょうか？
そもそも閲覧モードでは削除できないと思いますが，それとは違う意味でしょうか？

その他は，このままで良いと思います．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。一部説明不足があり申し訳ありません。

> secondary annotationを削除する

こちらですが（例えば間違えてLoadしてしまった時に）削除できるといいかなーと思った次第でした。Primary AnnotationのDELボタンのような挙動を想定しました。

不要そうでしたら無しでお願いします。
どうぞ宜しくお願いします。

**Comment by hshindo** [comment]
有難うございます．
いったんこのままにして，また削除の必要が出てきたらお願いしたいと思います．

**Comment by yoheiMune** [comment]
了解致しました。
確認ありがとうございます。
