### ISSUE TITLE
spanのラベル

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#8]
矢印と同様に，ハイライト（span）にもラベルテキストを割り当てるようにしたいと思います．
annoファイルの，"spanのテキスト"という部分に対応しています．

htmlannoではすでに実装ができているので，そちらを参考にしていただけないでしょうか．
https://pdfanno.github.io/htmlanno/journal.pbio.1001745.html

**Comment by yoheiMune** [comment]
了解致しました。

**Comment by yoheiMune** [comment]
お疲れ様です。
spanのラベルについて実装を行いました。こちらで認識合っていますかご確認お願いできますでしょうか？
（htmlannoを参照して実装しています）
https://paperai.github.io/paperanno/

どうぞよろしくお願いします。

**Comment by hshindo** [comment]
有難うございます．これでＯＫです．

おおよそ現在の実装で問題ないのですが，スパンのラベルを全てpdf上に表示するか，またはマウスオーバー時のみ表示させるか等，少し考えたいと思いますので，その間に他のissueをご対応いただけないでしょうか．
よろしくお願いします．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
了解致しました。

**Comment by hshindo** [comment]
一旦closeします．
