### ISSUE TITLE
バージョン情報をannoファイルへ付与

### ISSUE THREAD

**Issue by hshindo** [paperai/paperanno-ja#9]
paperannoのバージョン情報をannoファイルへ付与したいと思います．

例えば，
```
{
  "version": "0.0.1",
  "a.pdf": {
    ...
  },
  "b.pdf": {
    ...
  }
}
```

**Comment by yoheiMune** [comment]
こちら了解致しました。現在 #2を対応中なので、それが終わってからの着手とさせて下さい。

実装にあたって何点か質問させて下さい。
・バージョンの初期値は「0.0.1」でよろしいでしょうか？
・どのようなケースでバージョンを上げれば良いでしょうか？ユーザーがエクスポートする度にインクリメントというイメージでしょうか？？？

お手数お掛けしますがよろしくお願いします。

**Comment by hshindo** [comment]
初期値は0.0.1で良いです．
paperannoをnpmに登録して，そのバージョンを使おうと思いますが，いかがでしょうか？

**Comment by yoheiMune** [comment]
了解です。npmでのバージョンは `package.json`で定義するバージョン番号になるので、ビルド時にそれをpaperannoにも埋め込むようにします。
よろしくお願いします。

**Comment by hshindo** [comment]
はい，package.jsonのバージョン番号を書き換えてビルドすれば，それに合わせて自動的にannoファイルに書き込まれるバージョン番号が変わるということで合っていますか？
それならば問題ありません．

**Comment by yoheiMune** [comment]
お疲れ様です。
こちら対応いたしました。お手すきの際にご確認お願いいたします。
https://paperai.github.io/paperanno/

どうぞよろしくお願いします。

**Comment by hshindo** [comment]
確認致しました．有難うございました．

**Comment by yoheiMune** [comment]
ご確認ありがとうございます。
